# -*- coding: utf-8 -*-
"""gene_data_util.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q7qh2JbCa1yctVxHcaVt6ntUasDBNkhn
"""

import numpy as np
import pandas as pd

def train_test_split_seq(data):
  seq_train = [x[1] for x in data["train"]]
  y_train = [x[2] for x in data["train"]]

  seq_test = [x[1] for x in data["test"]]
  y_test = [x[2] for x in data["test"]]

  return seq_train, y_train, seq_test, y_test

def mean_median_calc(sequence):
  seq_len = [len(s) for s in sequence]
  mean = np.mean(seq_len)
  median = np.median(seq_len)
  return mean, median

def unique_value_count(sequence):
  sequence_int = list(map(int, sequence))
  non_resistant = sequence_int.count(0)
  resistant = sequence_int.count(1)
  return non_resistant, resistant